#!/usr/bin/env python
# -*- coding: utf-8 -*-

###################################################
# remove header of the sam file generated by gem  #
###################################################

import sys

with open(sys.argv[1]) as f:
   for line in f:
      header = line[0]
      if header == "@":
         continue
      sys.stdout.write(line)
